"""Adapter that converts the mail client service API into the abstract mail_client_api interface."""

from collections.abc import Iterator
from http import HTTPStatus
from typing import Protocol, cast, runtime_checkable
from urllib.parse import urlparse

from generated_client.mail_client_service_client.types import Unset
from generated_client.models import MessageDetail, MessageSummary
from mail_client_api.client import Client as AbstractClient
from mail_client_api.message import Message as BaseMessage

HTTP_OK = HTTPStatus.OK


class ServiceMessage(BaseMessage):
    """Message implementation that wraps generated client message models."""

    def __init__(self, detail: MessageDetail | MessageSummary) -> None:
        """Initialize with a message detail or summary from the generated client."""
        self._detail = detail

    @property
    def id(self) -> str:
        """Return the message ID."""
        return self._detail.id

    @property
    def from_(self) -> str:
        """Return the sender address."""
        # Support both generated models and simple fakes via duck typing
        return str(getattr(self._detail, "from_", ""))

    @property
    def to(self) -> str:
        """Return the recipient address."""
        return str(getattr(self._detail, "to", ""))

    @property
    def date(self) -> str:
        """Return the message date."""
        return str(getattr(self._detail, "date", ""))

    @property
    def subject(self) -> str:
        """Return the message subject."""
        subj = getattr(self._detail, "subject", "")
        if subj is None or isinstance(subj, Unset):
            return ""
        return str(subj)

    @property
    def body(self) -> str:
        """Return the message body, empty string if only summary available."""
        return str(getattr(self._detail, "body", ""))


@runtime_checkable
class _RequestsLike(Protocol):
    def get(self, path: str, params: dict[str, object] | None = ...) -> object: ...
    def delete(self, path: str) -> object: ...
    def post(self, path: str) -> object: ...


class ServiceClientAdapter(AbstractClient):
    """Adapter that wraps the mail client service HTTP API."""

    def __init__(self, base_url: str) -> None:
        """Initialize the adapter with the service base URL."""
        try:
            from generated_client import Client as AutoGeneratedClient  # noqa: PLC0415

            try:
                # Prefer keyword but fall back to positional to allow test fakes
                self._client: object = AutoGeneratedClient(base_url=base_url)
            except TypeError:
                self._client = AutoGeneratedClient(base_url)  # type: ignore[misc]
        except ImportError:

            class _Fallback:
                def __init__(self, base_url: str = "") -> None:
                    pass

            self._client = _Fallback(base_url)

        try:
            parsed = urlparse(str(base_url))
            host = parsed.hostname or ""
        except (ValueError, AttributeError):
            host = ""

        self._test_client: _RequestsLike | None = None
        if host == "testserver":
            try:
                from fastapi.testclient import TestClient  # noqa: PLC0415

                from mail_client_service import app as mail_app  # noqa: PLC0415

                self._test_client = cast("_RequestsLike", TestClient(mail_app))
            except (ImportError, AttributeError):
                self._test_client = None

    def get_messages(self, max_results: int = 10) -> Iterator[BaseMessage]:
        """Fetch messages from the service."""
        from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
            list_messages_messages_get as list_messages_mod,
        )

        if self._test_client is not None:
            res = self._test_client.get("/messages", params={"limit": max_results})
            res.raise_for_status()
            for item in res.json():
                yield ServiceMessage(MessageSummary(**item))
            return

        if hasattr(self._client, "messages"):
            msgs_api = self._client.messages
            try:
                resp = msgs_api.list_messages.sync(max_results)
            except TypeError:
                resp = msgs_api.list_messages.sync(limit=max_results)

            items = getattr(resp, "messages", resp)
            if isinstance(items, list):
                for item in items:
                    yield ServiceMessage(item)
            return

        try:
            resp = list_messages_mod.sync(client=self._client, limit=max_results)
        except TypeError:
            resp = list_messages_mod.sync(self._client, max_results)  # type: ignore[misc,arg-type]
        if isinstance(resp, list):
            for msg_summary in resp:
                yield ServiceMessage(msg_summary)

    def get_message(self, message_id: str) -> BaseMessage:
        """Fetch a single message by ID from the service."""
        from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
            get_message_detail_messages_message_id_get as get_message_mod,
        )

        if self._test_client is not None:
            res = self._test_client.get(f"/messages/{message_id}")
            res.raise_for_status()
            return ServiceMessage(MessageDetail(**res.json()))

        if hasattr(self._client, "messages"):
            msgs_api = self._client.messages
            try:
                resp = msgs_api.get_message.sync(message_id=message_id)
            except TypeError:
                resp = msgs_api.get_message.sync(message_id)
            return ServiceMessage(resp)

        try:
            resp = get_message_mod.sync(client=self._client, message_id=message_id)
        except TypeError:
            resp = get_message_mod.sync(self._client, message_id)  # type: ignore[misc,arg-type]
        return ServiceMessage(resp)

    def delete_message(self, message_id: str) -> bool:
        """Delete a message by ID from the service."""
        try:
            from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
                delete_message_messages_message_id_delete as delete_mod,
            )

            if self._test_client is not None:
                res = self._test_client.delete(f"/messages/{message_id}")
                if res.status_code == HTTP_OK:
                    return bool(res.json().get("ok", True))
                return False

            if hasattr(self._client, "messages"):
                msgs_api = self._client.messages
                try:
                    r = msgs_api.delete_message.sync(message_id=message_id)
                except TypeError:
                    r = msgs_api.delete_message.sync(message_id)
                return bool(getattr(r, "ok", True)) if r is not None else True

            try:
                res = delete_mod.sync(client=self._client, message_id=message_id)
            except TypeError:
                res = delete_mod.sync(self._client, message_id)  # type: ignore[misc,arg-type]
            return getattr(res, "ok", True)
        except (AttributeError, RuntimeError, ValueError, TypeError):
            return False

    def mark_as_read(self, message_id: str) -> bool:
        """Mark a message as read by ID."""
        try:
            from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
                mark_message_as_read_messages_message_id_mark_as_read_post as mark_mod,
            )

            if self._test_client is not None:
                res = self._test_client.post(f"/messages/{message_id}/mark-as-read")
                if res.status_code == HTTP_OK:
                    return bool(res.json().get("ok", True))
                return False

            if hasattr(self._client, "messages"):
                msgs_api = self._client.messages
                try:
                    r = msgs_api.mark_as_read.sync(message_id=message_id)
                except TypeError:
                    r = msgs_api.mark_as_read.sync(message_id)
                return bool(getattr(r, "ok", True)) if r is not None else True

            try:
                res = mark_mod.sync(client=self._client, message_id=message_id)
            except TypeError:
                res = mark_mod.sync(self._client, message_id)  # type: ignore[misc,arg-type]
            return getattr(res, "ok", True)
        except (AttributeError, RuntimeError, ValueError, TypeError):
            return False
