"""Auto-generated client for OpenAI Client Service API."""

__all__ = ["Client", "AuthenticatedClient"]
__version__ = "0.1.0"

# This file will be auto-generated by openapi-python-client
# Import the generated client classes here once generated

