import types

import pytest


@pytest.mark.unit
def test_service_message_and_adapter_roundtrip(monkeypatch) -> None:
    # Import under test
    from adapter.service_client_adapter import ServiceClientAdapter

    # Create fake generated models
    class FakeSummary:
        def __init__(self, id: str, subject: str):
            self.id = id
            self.subject = subject

    class FakeDetail:
        def __init__(self, id: str, from_: str, to: str, date: str, subject: str, body: str):
            self.id = id
            self.from_ = from_
            self.to = to
            self.date = date
            self.subject = subject
            self.body = body

    # Fake generated client with the same shape used by ServiceClientAdapter
    fake_api = types.SimpleNamespace()

    def list_messages_sync(max_results: int = 10):
        return types.SimpleNamespace(messages=[FakeSummary("m1", "s1"), FakeSummary("m2", "s2")])

    def get_message_sync(message_id: str):
        return FakeDetail(message_id, "a@b.com", "me@me.com", "2025-01-01T00:00:00Z", "sub", "body")

    msgs_api = types.SimpleNamespace(list_messages=types.SimpleNamespace(sync=list_messages_sync))
    get_api = types.SimpleNamespace(get_message=types.SimpleNamespace(sync=get_message_sync))
    delete_api = types.SimpleNamespace(delete_message=types.SimpleNamespace(sync=lambda **kw: None))
    mark_api = types.SimpleNamespace(mark_as_read=types.SimpleNamespace(sync=lambda **kw: None))

    fake_api.messages = types.SimpleNamespace(list_messages=types.SimpleNamespace(sync=list_messages_sync), get_message=types.SimpleNamespace(sync=get_message_sync), delete_message=types.SimpleNamespace(sync=lambda **kw: None), mark_as_read=types.SimpleNamespace(sync=lambda **kw: None))

    # Monkeypatch the AutoGeneratedClient used in the adapter to return our fake_api
    class FakeClient:
        def __init__(self, base_url: str = "http://x"):
            self.messages = fake_api.messages

    monkeypatch.setitem(__import__("sys").modules, "generated_client", types.SimpleNamespace(Client=FakeClient))

    # Now construct adapter and exercise methods
    adapter = ServiceClientAdapter(base_url="http://x")

    msgs = list(adapter.get_messages(max_results=10))
    assert len(msgs) == 2
    assert msgs[0].id == "m1"

    detail = adapter.get_message("m1")
    assert detail.id == "m1"
    assert detail.from_ == "a@b.com"

    assert adapter.mark_as_read("m1") is True
    assert adapter.delete_message("m1") is True




